version: '3.5'

services:
  # App
  app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      web:
        aliases:
          - app

  # Database
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword
    networks:
      web:
        aliases:
          - db

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: securerootpassword 
    networks:
      web:
        aliases:
          - phpmyadmin

networks:
  web:
    name: web-network